### ISSUE TITLE
请教：panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by alexallen1** [XrayR-project/XrayR#106]
您好，Xray在debian用得很穩定
然後，我嘗試了下，在境外公网一台工控機 linux BSD ，root下 755 單獨執行  ./XrarR & 
也能跑起来。但持续不够一天会挂，挂之前有下面显示。小弟水平不够看不懂，请教解决方式~

```
2022/01/25 21:07:39 0 user deleted, 0 user added
2022/01/25 21:07:41 Report 2 online users
2022/01/25 21:08:39 0 user deleted, 0 user added
2022/01/25 21:08:41 Report 2 online users
2022/01/25 21:09:41 0 user deleted, 0 user added
2022/01/25 21:09:41 Report 2 online users
2022/01/25 21:10:41 get cpu usage failed: received two CPU counts: 1 != 0
2022/01/25 21:10:42 Report 2 online users
2022/01/25 21:10:42 0 user deleted, 0 user added
panic: runtime error: index out of range [0] with length 0
goroutine 1350133 [running]:
github.com/XrayR-project/XrayR/common/serverstatus.GetSystemInfo(0xc0118fa750, 0xc00acccdf0, 0x6e3c25, 0x19743a0, 0x0, 0x0)
	github.com/XrayR-project/XrayR/common/serverstatus/serverstatus.go:33 +0x40c
github.com/XrayR-project/XrayR/service/controller.(*Controller).userInfoMonitor(0xc00032dae0, 0x1d93fa0, 0xc00074e8e0)
	github.com/XrayR-project/XrayR/service/controller/controller.go:314 +0x37
github.com/xtls/xray-core/common/task.(*Periodic).checkedExecute(0xc00074e8d0, 0x0, 0x0)
	github.com/xtls/xray-core@v1.4.2/common/task/periodic.go:32 +0x5e
github.com/xtls/xray-core/common/task.(*Periodic).checkedExecute.func1()
	github.com/xtls/xray-core@v1.4.2/common/task/periodic.go:47 +0x2a
created by time.goFunc
	time/sleep.go:180 +0x45
```

**Comment by RManLuo** [comment]
似乎是获取系统信息时出错了，尝试以root权限运行软件。并提供一下相关系统信息，如Linux版本号。

**Comment by alexallen1** [comment]
Linux DS420 4.4.59+ #25556 SMP PREEMPT Thu Mar 18 13:00:34 CST 2021 x86_64 GNU/Linux synology_geminilake_420+

**Comment by RManLuo** [comment]
似乎对于部分FreeBSD系统，获取CPU时间的功能没有办法很好支持。shirou/gopsutil#893

**Comment by alexallen1** [comment]
请问有无命令可以不get cpu usage~

**Comment by thank243** [comment]
> 请问有无命令可以不get cpu usage~
只能修改代码， 或者等 https://github.com/shirou/gopsutil/pull/893 修复。
