### ISSUE TITLE
xrayr重启失败，找不到文件

### ISSUE THREAD

**Issue by camghaitan** [XrayR-project/XrayR#139]
Mar 17 15:50:14 VM21514 systemd[1]: XrayR.service: Scheduled restart job, restart counter is at 7980.
Mar 17 15:50:14 VM21514 systemd[1]: Stopped XrayR Service.
Mar 17 15:50:14 VM21514 systemd[1]: Started XrayR Service.
Mar 17 15:50:14 VM21514 XrayR[559546]: XrayR 0.7.6 (A Xray backend that supports many panels)
Mar 17 15:50:14 VM21514 XrayR[559546]: 2022/03/17 15:50:14 Start the panel..
Mar 17 15:50:14 VM21514 XrayR[559546]: 2022/03/17 15:50:14 Failed to read file at:
Mar 17 15:50:14 VM21514 XrayR[559546]: panic: Failed to read file at:
Mar 17 15:50:14 VM21514 XrayR[559546]: goroutine 1 [running]:
Mar 17 15:50:14 VM21514 XrayR[559546]: log.Panicf({0x2096c69, 0xc0001c4a20}, {0xc0000b9c18, 0x1c96f40, 0xc000088e60})
Mar 17 15:50:14 VM21514 XrayR[559546]:         log/log.go:361 +0x67
Mar 17 15:50:14 VM21514 XrayR[559546]: github.com/XrayR-project/XrayR/panel.(*Panel).loadCore(0xc0005bfea0, 0xc0000cb3b0)
Mar 17 15:50:14 VM21514 XrayR[559546]:         github.com/XrayR-project/XrayR/panel/panel.go:88 +0x4bd
Mar 17 15:50:14 VM21514 XrayR[559546]: github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc0005475c0)
Mar 17 15:50:14 VM21514 XrayR[559546]:         github.com/XrayR-project/XrayR/panel/panel.go:157 +0xe9
Mar 17 15:50:14 VM21514 XrayR[559546]: main.main()
Mar 17 15:50:14 VM21514 XrayR[559546]:         github.com/XrayR-project/XrayR/main/main.go:92 +0x1ed
Mar 17 15:50:14 VM21514 systemd[1]: XrayR.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 17 15:50:14 VM21514 systemd[1]: XrayR.service: Failed with result 'exit-code'.

**Comment by camghaitan** [comment]
log文件说读取不到文件，但是我不知道读取不到什么文件

**Comment by camghaitan** [comment]
有大佬知道吗
