### ISSUE TITLE
输出配置文件读取失败，重装了还是不行

### ISSUE THREAD

**Issue by camghaitan** [XrayR-project/XrayR#142]
Mar 18 21:08:39 VM21514 systemd[1]: XrayR.service: Scheduled restart job, restart counter is at 119.
Mar 18 21:08:39 VM21514 systemd[1]: Stopped XrayR Service.
Mar 18 21:08:39 VM21514 systemd[1]: Started XrayR Service.
Mar 18 21:08:39 VM21514 XrayR[16518]: XrayR 0.7.6 (A Xray backend that supports many panels)
Mar 18 21:08:39 VM21514 XrayR[16518]: 2022/03/18 21:08:39 Start the panel..
Mar 18 21:08:39 VM21514 XrayR[16518]: 2022/03/18 21:08:39 Failed to read file at: /etc/XrayR/custom_outbound.json
Mar 18 21:08:39 VM21514 XrayR[16518]: panic: Failed to read file at: /etc/XrayR/custom_outbound.json
Mar 18 21:08:39 VM21514 XrayR[16518]: goroutine 1 [running]:
Mar 18 21:08:39 VM21514 XrayR[16518]: log.Panicf({0x2096c69, 0x1f}, {0xc000341c18, 0x1c96f40, 0xc00007ae60})
Mar 18 21:08:39 VM21514 XrayR[16518]:         log/log.go:361 +0x67
Mar 18 21:08:39 VM21514 XrayR[16518]: github.com/XrayR-project/XrayR/panel.(*Panel).loadCore(0xc00053fea0, 0xc0000bbc00)
Mar 18 21:08:39 VM21514 XrayR[16518]:         github.com/XrayR-project/XrayR/panel/panel.go:88 +0x4bd
Mar 18 21:08:39 VM21514 XrayR[16518]: github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc00056f900)
Mar 18 21:08:39 VM21514 XrayR[16518]:         github.com/XrayR-project/XrayR/panel/panel.go:157 +0xe9
Mar 18 21:08:39 VM21514 XrayR[16518]: main.main()
Mar 18 21:08:39 VM21514 XrayR[16518]:         github.com/XrayR-project/XrayR/main/main.go:92 +0x1ed
Mar 18 21:08:39 VM21514 systemd[1]: XrayR.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 18 21:08:39 VM21514 systemd[1]: XrayR.service: Failed with result 'exit-code'.

**Comment by camghaitan** [comment]
[
    {
        "tag": "IPv4_out",
        "protocol": "freedom"
    },
    {
        "tag": "IPv6_out",
        "protocol": "freedom",
        "settings": {
            "domainStrategy": "UseIPv6"
        }
    },
    {
        "protocol": "blackhole",
        "tag": "block"
    }
]

**Comment by camghaitan** [comment]
输出配置文件是重装完后的文件，没有更改过，之前也是这个文件，可以运行

**Comment by camghaitan** [comment]
custom_inbound.json或者custom_outbound.json文件有问题，都会出现这个错误
