### ISSUE TITLE
使用V2board 1.71版本，对接xrayr0.8.8版本后端  返回 (code=exited, status=2)

### ISSUE THREAD

**Issue by Amone0012** [XrayR-project/XrayR#167]
使用V2board 1.71版本，对接xrayr0.8.8版本后端，选取NewV2board面板对接，apikey核对过多次，节点ID也核对过多次，均无法成功运行

xrayr日志：
![image](https://user-images.githubusercontent.com/96175998/208236066-c16fd4af-0987-45cc-a8c0-47de921bfcbd.png)

其中    "message": "\u9047\u5230\u4e86\u4e9b\u95ee\u9898\uff0c\u6211\u4eec\u6b63\u5728\u8fdb\u884c\u5904\u7406"
转中文得到：“遇到了些问题，我们正在进行处理”

查看xrayr后端状态返回为：
![image](https://user-images.githubusercontent.com/96175998/208235986-bcd591a8-15b4-4200-a48f-2fd333968914.png)

**Comment by thank243** [comment]
You can use `curl` command to test your API. If yout get the same response, you should goto panel's group to ask this question instead of the xrayr group.

**Comment by Susana6575** [comment]
v2b v1.7.1 升级至开发版可解决

**Comment by ImanAmeli** [comment]
i have same problem anyone can help me?

```
Dec 20 04:31:52 ubuntu-g2-small1-sh-1 systemd[1]: Started XrayR Service.
Dec 20 04:31:52 ubuntu-g2-small1-sh-1 XrayR[9905]: XrayR 0.8.8 (A Xray backend that supports many panels)
Dec 20 04:31:52 ubuntu-g2-small1-sh-1 XrayR[9905]: 2022/12/20 04:31:52 Parse config file 0xc0001e5c80 failed: 1 error(s) decoding:
Dec 20 04:31:52 ubuntu-g2-small1-sh-1 XrayR[9905]: * cannot parse 'Nodes[0].ApiConfig.NodeID' as int: strconv.ParseInt: parsing "11 => 5": invalid syntax
Dec 20 04:31:52 ubuntu-g2-small1-sh-1 XrayR[9905]: panic: Parse config file 0xc0001e5c80 failed: 1 error(s) decoding:
Dec 20 04:31:52 ubuntu-g2-small1-sh-1 XrayR[9905]: * cannot parse 'Nodes[0].ApiConfig.NodeID' as int: strconv.ParseInt: parsing "11 => 5": invalid syntax
Dec 20 04:31:52 ubuntu-g2-small1-sh-1 XrayR[9905]: goroutine 1 [running]:
Dec 20 04:31:52 ubuntu-g2-small1-sh-1 XrayR[9905]: log.Panicf({0x31a9a9f?, 0x2691e60?}, {0xc000939f18?, 0x0?, 0x0?})
Dec 20 04:31:52 ubuntu-g2-small1-sh-1 XrayR[9905]:         log/log.go:395 +0x67
Dec 20 04:31:52 ubuntu-g2-small1-sh-1 XrayR[9905]: main.main()
Dec 20 04:31:52 ubuntu-g2-small1-sh-1 XrayR[9905]:         github.com/XrayR-project/XrayR/main/main.go:78 +0x130
Dec 20 04:31:52 ubuntu-g2-small1-sh-1 systemd[1]: XrayR.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 20 04:31:52 ubuntu-g2-small1-sh-1 systemd[1]: XrayR.service: Failed with result 'exit-code'.
Dec 20 04:32:02 ubuntu-g2-small1-sh-1 systemd[1]: XrayR.service: Scheduled restart job, restart counter is at 462.
Dec 20 04:32:02 ubuntu-g2-small1-sh-1 systemd[1]: Stopped XrayR Service.

```
