### ISSUE TITLE
panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by ddaodan** [XrayR-project/XrayR#19]
安装后无法启动

日志内容：

Jul 28 12:11:21 localhost systemd[1]: Stopped XrayR Service.
Jul 28 12:11:21 localhost systemd[1]: Started XrayR Service.
Jul 28 12:11:21 localhost XrayR[117953]: XrayR 0.8.0 (A Xray backend that supports many panels)
Jul 28 12:11:21 localhost XrayR[117953]: 2022/07/28 12:11:21 Start the panel..
Jul 28 12:11:21 localhost XrayR[117953]: 2022/07/28 12:11:21 Xray Core Version: 1.5.4
Jul 28 12:11:21 localhost XrayR[117953]: 2022/07/28 12:11:21 [Debug] app/log: Logger started
Jul 28 12:11:21 localhost XrayR[117953]: 2022/07/28 12:11:21 [Info] app/dns: DNS: created localhost client
Jul 28 12:11:21 localhost XrayR[117953]: 2022/07/28 12:11:21 [Warning] core: Xray 1.5.4 started
Jul 28 12:11:21 localhost XrayR[117953]: 2022/07/28 12:11:21 [Debug] app/proxyman/inbound: creating stream worker on 0.0.0.0:1000
Jul 28 12:11:21 localhost XrayR[117953]: 2022/07/28 12:11:21 [Info] transport/internet/tcp: listening TCP on 0.0.0.0:1000
Jul 28 12:11:22 localhost XrayR[117953]: panic: runtime error: index out of range [0] with length 0
Jul 28 12:11:22 localhost XrayR[117953]: goroutine 1 [running]:
Jul 28 12:11:22 localhost XrayR[117953]: github.com/XrayR-project/XrayR/service/controller.(*Controller).addNewUser(0xc00013ac80, 0xc00001bec0, 0xc00053fd68?)
Jul 28 12:11:22 localhost XrayR[117953]:         github.com/XrayR-project/XrayR/service/controller/controller.go:339 +0x2cf
Jul 28 12:11:22 localhost XrayR[117953]: github.com/XrayR-project/XrayR/service/controller.(*Controller).Start(0xc00013ac80)
Jul 28 12:11:22 localhost XrayR[117953]:         github.com/XrayR-project/XrayR/service/controller/controller.go:64 +0x2a9
Jul 28 12:11:22 localhost XrayR[117953]: github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc00009e480)
Jul 28 12:11:22 localhost XrayR[117953]:         github.com/XrayR-project/XrayR/panel/panel.go:192 +0x59a
Jul 28 12:11:22 localhost XrayR[117953]: main.main()
Jul 28 12:11:22 localhost XrayR[117953]:         github.com/XrayR-project/XrayR/main/main.go:92 +0x1ed
Jul 28 12:11:22 localhost systemd[1]: XrayR.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 28 12:11:22 localhost systemd[1]: XrayR.service: Failed with result 'exit-code'.
Jul 28 12:11:31 localhost systemd[1]: Stopped XrayR Service.

**Comment by ddaodan** [comment]
不知道为啥重新装了一遍就好了。。。
