### ISSUE TITLE
使用xtls流控xtls-rprx-direct-udp443作为xrayr 的上游代理报错

### ISSUE THREAD

**Issue by OPPO9008** [XrayR-project/XrayR#200]
中转分流机搭建了xrayr，outbound使用了xtls 流控xtls-rprx-direct-udp443，以前不会报错现在报错了

```
Jan 08 15:56:15 6sLCjfhPOS XrayR[3432242]: 2023/01/08 15:56:15 113.127.157.231:0 accepted tcp:[2001::9a53:f2d]:443 [V2ray_127.0.0.1_8081 -> xtls] email: V2ray_127.0.0.1_8081||1
Jan 08 15:56:16 6sLCjfhPOS XrayR[3432242]: panic: XTLS Splice: not TCP inbound
Jan 08 15:56:16 6sLCjfhPOS XrayR[3432242]: goroutine 134 [running]:
Jan 08 15:56:16 6sLCjfhPOS XrayR[3432242]: github.com/xtls/xray-core/proxy/vless/encoding.ReadV.func1(0xc0025c53e8, {0x33e7af0, 0xc00180ef80}, {0x0, 0x0}, {0x33e6900?, 0xc0025c53f0}, 0xc000d01da0, {0x33b7740, 0xc000ac8bd0}, ...)
Jan 08 15:56:16 6sLCjfhPOS XrayR[3432242]:         github.com/xtls/xray-core@v1.6.3/proxy/vless/encoding/encoding.go:218 +0x655
Jan 08 15:56:16 6sLCjfhPOS XrayR[3432242]: github.com/xtls/xray-core/proxy/vless/encoding.ReadV({0x33b7340, 0xc0025c9780}, {0x33b3fc0?, 0xc0018885c0?}, {0x33b7740?, 0xc000ac8bd0?}, 0x0?, {0x33e6900?, 0xc0025c53f0?}, {0x0, ...}, ...)
Jan 08 15:56:16 6sLCjfhPOS XrayR[3432242]:         github.com/xtls/xray-core@v1.6.3/proxy/vless/encoding/encoding.go:241 +0xa5
Jan 08 15:56:16 6sLCjfhPOS XrayR[3432242]: github.com/xtls/xray-core/proxy/vless/outbound.(*Handler).Process.func3()
Jan 08 15:56:16 6sLCjfhPOS XrayR[3432242]:         github.com/xtls/xray-core@v1.6.3/proxy/vless/outbound/outbound.go:282 +0x5ee
Jan 08 15:56:16 6sLCjfhPOS XrayR[3432242]: github.com/xtls/xray-core/common/task.OnSuccess.func1()
Jan 08 15:56:16 6sLCjfhPOS XrayR[3432242]:         github.com/xtls/xray-core@v1.6.3/common/task/task.go:12 +0x25
Jan 08 15:56:16 6sLCjfhPOS XrayR[3432242]: github.com/xtls/xray-core/common/task.Run.func1(0x1c?)
Jan 08 15:56:16 6sLCjfhPOS XrayR[3432242]:         github.com/xtls/xray-core@v1.6.3/common/task/task.go:28 +0x2e
Jan 08 15:56:16 6sLCjfhPOS XrayR[3432242]: created by github.com/xtls/xray-core/common/task.Run
Jan 08 15:56:16 6sLCjfhPOS XrayR[3432242]:         github.com/xtls/xray-core@v1.6.3/common/task/task.go:27 +0xde

```

**Comment by thank243** [comment]
You can use `xray-core` to test this feat. If you got the same panic, you should goto xray-core group for helping. Xtls official suggests use `xtls-rprx-direct`.
