### ISSUE TITLE
reality outbound after update to commit 169f742

### ISSUE THREAD

**Issue by MrVb0** [XrayR-project/XrayR#328]
Hello
Thank you for adding reality @thank243 
I after update to commit 169f742 tried to use reality in outbound, but xrayr gets this error:

```
Apr 22 17:50:27 localhost.localdomain systemd[1]: Unit XrayR.service entered failed state.
Apr 22 17:50:27 localhost.localdomain systemd[1]: XrayR.service failed.
Apr 22 17:50:37 localhost.localdomain systemd[1]: XrayR.service holdoff time over, scheduling restart.
Apr 22 17:50:37 localhost.localdomain systemd[1]: Stopped XrayR Service.
Apr 22 17:50:37 localhost.localdomain systemd[1]: Started XrayR Service.
Apr 22 17:50:37 localhost.localdomain XrayR[16131]: XrayR 0.9.0 (A Xray backend that supports many panels)
Apr 22 17:50:37 localhost.localdomain XrayR[16131]: 2023/04/22 17:50:37 Start the panel..
Apr 22 17:50:37 localhost.localdomain XrayR[16131]: 2023/04/22 17:50:37 Failed to unmarshal Custom Outbound config: /etc/XrayR/custom_outbound.json
Apr 22 17:50:37 localhost.localdomain XrayR[16131]: panic: Failed to unmarshal Custom Outbound config: /etc/XrayR/custom_outbound.json
Apr 22 17:50:37 localhost.localdomain XrayR[16131]: goroutine 1 [running]:
Apr 22 17:50:37 localhost.localdomain XrayR[16131]: log.Panicf({0x331e25d?, 0x1f?}, {0xc0005d3bc8?, 0x27be0e0?, 0xc000643e78?})
Apr 22 17:50:37 localhost.localdomain XrayR[16131]: log/log.go:391 +0x67
Apr 22 17:50:37 localhost.localdomain XrayR[16131]: github.com/XrayR-project/XrayR/panel.(*Panel).loadCore(0xc000745e80?, 0xc000196e00)
Apr 22 17:50:37 localhost.localdomain XrayR[16131]: github.com/XrayR-project/XrayR/panel/panel.go:121 +0x78e
Apr 22 17:50:37 localhost.localdomain XrayR[16131]: github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc000454880)
Apr 22 17:50:37 localhost.localdomain XrayR[16131]: github.com/XrayR-project/XrayR/panel/panel.go:168 +0xe9
Apr 22 17:50:37 localhost.localdomain XrayR[16131]: main.main()
Apr 22 17:50:37 localhost.localdomain XrayR[16131]: github.com/XrayR-project/XrayR/main/main.go:97 +0x250
Apr 22 17:50:37 localhost.localdomain systemd[1]: XrayR.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 22 17:50:37 localhost.localdomain systemd[1]: Unit XrayR.service entered failed state.
Apr 22 17:50:37 localhost.localdomain systemd[1]: XrayR.service failed.
Apr 22 17:50:47 localhost.localdomain systemd[1]: XrayR.service holdoff time over, scheduling restart.
Apr 22 17:50:47 localhost.localdomain systemd[1]: Stopped XrayR Service.
Apr 22 17:50:47 localhost.localdomain systemd[1]: Started XrayR Service.
Apr 22 17:50:47 localhost.localdomain XrayR[16166]: XrayR 0.9.0 (A Xray backend that supports many panels)
Apr 22 17:50:47 localhost.localdomain XrayR[16166]: 2023/04/22 17:50:47 Start the panel..
Apr 22 17:50:47 localhost.localdomain XrayR[16166]: 2023/04/22 17:50:47 Failed to unmarshal Custom Outbound config: /etc/XrayR/custom_outbound.json
Apr 22 17:50:47 localhost.localdomain XrayR[16166]: panic: Failed to unmarshal Custom Outbound config: /etc/XrayR/custom_outbound.json
Apr 22 17:50:47 localhost.localdomain XrayR[16166]: goroutine 1 [running]:
Apr 22 17:50:47 localhost.localdomain XrayR[16166]: log.Panicf({0x331e25d?, 0x1f?}, {0xc00010fbc8?, 0x27be0e0?, 0xc001251908?})
Apr 22 17:50:47 localhost.localdomain XrayR[16166]: log/log.go:391 +0x67
Apr 22 17:50:47 localhost.localdomain XrayR[16166]: github.com/XrayR-project/XrayR/panel.(*Panel).loadCore(0xc0005a3e80?, 0xc0004f6000)
Apr 22 17:50:47 localhost.localdomain XrayR[16166]: github.com/XrayR-project/XrayR/panel/panel.go:121 +0x78e
Apr 22 17:50:47 localhost.localdomain XrayR[16166]: github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc0005a8640)
Apr 22 17:50:47 localhost.localdomain XrayR[16166]: github.com/XrayR-project/XrayR/panel/panel.go:168 +0xe9
Apr 22 17:50:47 localhost.localdomain XrayR[16166]: main.main()
Apr 22 17:50:47 localhost.localdomain XrayR[16166]: github.com/XrayR-project/XrayR/main/main.go:97 +0x250
Apr 22 17:50:47 localhost.localdomain systemd[1]: XrayR.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 22 17:50:47 localhost.localdomain systemd[1]: Unit XrayR.service entered failed state.
Apr 22 17:50:47 localhost.localdomain systemd[1]: XrayR.service failed.
```

**Comment by thank243** [comment]
paste /etc/XrayR/custom_outbound.json file.

**Comment by MrVb0** [comment]
[
  {
    "tag": "direct",
    "protocol": "freedom"
  },
  {
    "tag": "proxy",
    "protocol": "vless",
    "settings": {
                  "vnext": [
                    {
                        "address": "**domain**",
                        "port": 443,
                        "users": [
                            {
                                "id": "**uuid**",
                                "encryption": "none",
                                "flow": "xtls-rprx-vision"
                            }
                        ]
                    }
                ]
  },
            "streamSettings": {
                "network": "tcp",
                "security": "reality",
                "realitySettings": {
                    "fingerprint": "chrome", 
                    "serverName": "**yahoo.com**",
                    "publicKey": "**publicKey**", 
                    "shortId": "", 
                    "spiderX": "" 
                }
  },
  
  {
    "tag": "socks5-warp",
    "protocol": "socks",
    "settings": {
      "servers": [
        {
          "address": "127.0.0.1",
          "port": 1080
        }
      ]
    }
  },
  {
    "protocol": "blackhole",
    "tag": "block"
  }
]

**Comment by MrVb0** [comment]
I used to easily use this type of configuration for vless+vision+tls and it worked without any problems

**Comment by thank243** [comment]
Try to use the latest xray-core to check your config is correctly.

**Comment by MrVb0** [comment]
I modeled my config from[ this link](https://github.com/XTLS/REALITY)

**Comment by thank243** [comment]
refer: [link](https://xrayr-project.github.io/XrayR-doc/gong-neng-shuo-ming/zi-ding-yi-chu-kou-gong-neng-shuo-ming.html)
