### ISSUE TITLE
runtime error by grpc-vless-tls

### ISSUE THREAD

**Issue by OPPO9008** [XrayR-project/XrayR#375]
这是我在sspanel 输入的节点配置，当该节点下发后会报错

`*******;2345;0;grpc;tls;host=****.xyz|server=****.xyz|servicename=*****|enable_vless=true` 
报错内容

```
Jun 04 20:08:38 vultr XrayR[2213840]: panic: runtime error: invalid memory address or nil pointer dereference
Jun 04 20:08:38 vultr XrayR[2213840]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x255a493]
Jun 04 20:08:38 vultr XrayR[2213840]: goroutine 1 [running]:
Jun 04 20:08:38 vultr XrayR[2213840]: github.com/XrayR-project/XrayR/service/controller.InboundBuilder(0xc000be4800, 0xc000172f00, {0xc000f3e060, 0x12})
Jun 04 20:08:38 vultr XrayR[2213840]:         github.com/XrayR-project/XrayR/service/controller/inboundbuilder.go:188 +0xdf3
Jun 04 20:08:38 vultr XrayR[2213840]: github.com/XrayR-project/XrayR/service/controller.(*Controller).addNewTag(0xc000588e00, 0xc000172f00)
Jun 04 20:08:38 vultr XrayR[2213840]:         github.com/XrayR-project/XrayR/service/controller/controller.go:302 +0x85
Jun 04 20:08:38 vultr XrayR[2213840]: github.com/XrayR-project/XrayR/service/controller.(*Controller).Start(0xc000588e00)
Jun 04 20:08:38 vultr XrayR[2213840]:         github.com/XrayR-project/XrayR/service/controller/controller.go:82 +0x237
Jun 04 20:08:38 vultr XrayR[2213840]: github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc0008c93c0)
Jun 04 20:08:38 vultr XrayR[2213840]:         github.com/XrayR-project/XrayR/panel/panel.go:209 +0x556
Jun 04 20:08:38 vultr XrayR[2213840]: main.main()
Jun 04 20:08:38 vultr XrayR[2213840]:         github.com/XrayR-project/XrayR/main/main.go:97 +0x250
Jun 04 20:08:38 vultr systemd[1]: XrayR.service: Main process exited, code=exited, status=2/INVALIDARGUMENT

```

**Comment by thank243** [comment]
Use the latest confg example.
