### ISSUE TITLE
出现 "x509: certificate signed by unknown authority, Attempt 1" 错误 

### ISSUE THREAD

**Issue by tanpengsccd** [XrayR-project/XrayR#39]
我的SSP面板 已经 替换为 www.baidu.com了 脱敏了. 

下面是日志
```
Jul 30 00:16:58 krl systemd[1]: XrayR.service: Scheduled restart job, restart counter is at 276.
Jul 30 00:16:58 krl systemd[1]: Stopped XrayR Service.
Jul 30 00:16:58 krl systemd[1]: Started XrayR Service.
Jul 30 00:16:58 krl XrayR[97510]: XrayR 0.6.1 (A Xray backend that supports many panels)
Jul 30 00:16:58 krl XrayR[97510]: 2021/07/30 00:16:58 Start the panel..
Jul 30 00:16:58 krl XrayR[97510]: 2021/07/30 00:16:58 Xray Core Version: 1.4.2
Jul 30 00:16:59 krl XrayR[97510]: 2021/07/30 00:16:59.196470 ERROR RESTY Get "https://www.baidu.com/mod_mu/nodes/1/info?key=Leonardo123&muKey=Leonardo123": x509: certificate signed by unknown authority, Attempt 1
Jul 30 00:16:59 krl XrayR[97510]: 2021/07/30 00:16:59.616536 ERROR RESTY Get "https://www.baidu.com/mod_mu/nodes/1/info?key=Leonardo123&muKey=Leonardo123": x509: certificate signed by unknown authority, Attempt 2
Jul 30 00:17:00 krl XrayR[97510]: 2021/07/30 00:17:00.106784 ERROR RESTY Get "https://www.baidu.com/mod_mu/nodes/1/info?key=Leonardo123&muKey=Leonardo123": x509: certificate signed by unknown authority, Attempt 3
Jul 30 00:17:00 krl XrayR[97510]: 2021/07/30 00:17:00.785357 ERROR RESTY Get "https://www.baidu.com/mod_mu/nodes/1/info?key=Leonardo123&muKey=Leonardo123": x509: certificate signed by unknown authority, Attempt 4
Jul 30 00:17:01 krl XrayR[97510]: 2021/07/30 00:17:01 Get "https://www.baidu.com/mod_mu/nodes/1/info?key=Leonardo123&muKey=Leonardo123": x509: certificate signed by unknown authority
Jul 30 00:17:01 krl XrayR[97510]: 2021/07/30 00:17:01 Panel Start fialed: request https://www.baidu.com/mod_mu/nodes/1/info failed: Get "https://www.baidu.com/mod_mu/nodes/1/info?key=Leonardo123&muKey=Leonardo123": x509: certificate signed by unknown authority
Jul 30 00:17:01 krl XrayR[97510]: panic: Panel Start fialed: request https://www.baidu.com/mod_mu/nodes/1/info failed: Get "https://www.baidu.com/mod_mu/nodes/1/info?key=Leonardo123&muKey=Leonardo123": x509: certificate signed by unknown authority
Jul 30 00:17:01 krl XrayR[97510]: goroutine 1 [running]:
Jul 30 00:17:01 krl XrayR[97510]: log.Panicf(0x1f5f5ab, 0x16, 0xc00067fea0, 0x1, 0x1)
Jul 30 00:17:01 krl XrayR[97510]:         log/log.go:361 +0xc5
Jul 30 00:17:01 krl XrayR[97510]: github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc000451680)
Jul 30 00:17:01 krl XrayR[97510]:         github.com/XrayR-project/XrayR/panel/panel.go:137 +0x6f1
Jul 30 00:17:01 krl XrayR[97510]: main.main()
Jul 30 00:17:01 krl XrayR[97510]:         github.com/XrayR-project/XrayR/main/main.go:85 +0x1c5
Jul 30 00:17:01 krl systemd[1]: XrayR.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 30 00:17:01 krl systemd[1]: XrayR.service: Failed with result 'exit-code'.
```

**Comment by crackair** [comment]
@tanpengsccd 自行确认证书有效情况，目测为宝塔申请的证书

**Comment by steamsv** [comment]
@tanpengsccd 你确定www.baidu.com是你的api地址？，这个域名解析是否归你控制，xs

**Comment by tanpengsccd** [comment]
确实是宝塔自己申请的证书有问题。我换acme的证书就好了。
