### ISSUE TITLE
ret {"ret":0,"data":null} invalid

### ISSUE THREAD

**Issue by 2018jm** [XrayR-project/XrayR#405]
XrayR 0.9.0 (A Xray backend that supports many panels)
2023/07/07 15:55:27 Start the panel..
2023/07/07 15:55:27 Xray Core Version: 1.7.5
2023/07/07 15:55:27 [Debug] app/log: Logger started
2023/07/07 15:55:27 [Info] app/dns: DNS: created localhost client
2023/07/07 15:55:27 [Warning] core: Xray 1.7.5 started
2023/07/07 15:55:27 Panel Start fialed: ret {"ret":0,"data":null} invalid
panic: Panel Start fialed: ret {"ret":0,"data":null} invalid

goroutine 1 [running]:
log.Panicf({0x3283dcd?, 0x3706700?}, {0xc0004fde80?, 0xc0002d1280?, 0x2b3a6c0?})
        log/log.go:391 +0x67
github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc0007d5b80)
        github.com/XrayR-project/XrayR/panel/panel.go:211 +0x59b
main.main()
        github.com/XrayR-project/XrayR/main/main.go:97 +0x250

使用docker安装出现报错

**Comment by 2018jm** [comment]
![image](https://github.com/XrayR-project/XrayR/assets/123924368/acdba432-42ac-4aa8-9fb7-dfc6ac0f6dca)
