### ISSUE TITLE
shadowsocks 模式下panic，可能是未获取到节点地址

### ISSUE THREAD

**Issue by duudukaka** [XrayR-project/XrayR#43]
面板：v2oard ，已套cf
ss模式
权限组：test，标签 112233，4455566
节点地址与后端ip一致（无ipv6）
为父节点

``` Log:
  Level: none # Log level: none, error, warning, info, debug 
  AccessPath: # ./access.Log
  ErrorPath: # ./error.log
DnsConfigPath:  /etc/XrayR/dns.json
ConnetionConfig:
  Handshake: 4 # Handshake time limit, Second
  ConnIdle: 30 # Connection idle time limit, Second
  UplinkOnly: 2 # Time limit when the connection downstream is closed, Second
  DownlinkOnly: 4 # Time limit when the connection is closed after the uplink is closed, Second
  BufferSize: 64 # The internal cache size of each connection, kB 
Nodes:
   -
     PanelType: "V2board" # Panel type: SSpanel, V2board
     ApiConfig:
       ApiHost: "http://baidu.com"
       ApiKey: "d2=5445444558255"
       NodeID: 1
       NodeType: Shadowsocks # Node type: V2ray, Shadowsocks, Trojan
       Timeout: 30 # Timeout for the api request
       EnableVless: false # Enable Vless for V2ray Type
       EnableXTLS: false # Enable XTLS for V2ray and Trojan
       SpeedLimit: 0 # Mbps, Local settings will replace remote settings
       DeviceLimit: 0 # Local settings will replace remote settings
     ControllerConfig:
       ListenIP: 0.0.0.0 # IP address you want to listen
       UpdatePeriodic: 10 # Time to update the nodeinfo, how many sec.
       EnableDNS: false # Use custom DNS config, Please ensure that you set the dns.json well
       CertConfig:
         CertMode: none # Option about how to get certificate: none, file, http, dns
         CertDomain: "node1.test.com" # Domain to cert
         CertFile: ./cert/node1.test.com.cert # Provided if the CertMode is file
         KeyFile: ./cert/node1.test.com.pem
         Provider: alidns # DNS cert provider, Get the full support list here: https://go-acme.github.io/lego/dns/
         Email: test@me.com
         DNSEnv: # DNS ENV option used by DNS provider
           ALICLOUD_ACCESS_KEY: aaa
           ALICLOUD_SECRET_KEY: bbb
```

报错：
```
Aug 18 01:40:40 cIc.cc systemd[1]: Started XrayR Service.
Aug 18 01:40:40 cIc.cc XrayR[119309]: XrayR 0.6.1 (A Xray backend that supports many panels)
Aug 18 01:40:40 cIc.cc XrayR[119309]: 2021/08/18 01:40:40 Start the panel..
Aug 18 01:40:40 cIc.cc XrayR[119309]: 2021/08/18 01:40:40 Xray Core Version: 1.4.2
Aug 18 01:40:41 cIc.cc XrayR[119309]: panic: Calling Domain() on an IPv4Address.
Aug 18 01:40:41 cIc.cc XrayR[119309]: goroutine 1 [running]:
Aug 18 01:40:41 cIc.cc XrayR[119309]: github.com/xtls/xray-core/common/net.ipv4Address.Domain(...)
Aug 18 01:40:41 cIc.cc XrayR[119309]:         github.com/xtls/xray-core@v1.4.2/common/net/address.go:132
Aug 18 01:40:41 cIc.cc XrayR[119309]: github.com/xtls/xray-core/transport/internet/tcp.ListenTCP(0x2289f70, 0xc00003e070, 0x228b630, 0xc00042ac30, 0xc0003d0000, 0xc00007aff0, 0xc00006b680, 0x10, 0x10, 0x7fe44a793108, ...)
Aug 18 01:40:41 cIc.cc XrayR[119309]:         github.com/xtls/xray-core@v1.4.2/transport/internet/tcp/hub.go:48 +0x103
Aug 18 01:40:41 cIc.cc XrayR[119309]: github.com/xtls/xray-core/transport/internet.ListenTCP(0x2289f70, 0xc00003e070, 0x228b630, 0xc00042ac30, 0x0, 0xc00007aff0, 0xc00006b680, 0xc000457440, 0xc00007ad20, 0x30cfbe0, ...)
Aug 18 01:40:41 cIc.cc XrayR[119309]:         github.com/xtls/xray-core@v1.4.2/transport/internet/tcp_hub.go:73 +0x29d
Aug 18 01:40:41 cIc.cc XrayR[119309]: github.com/xtls/xray-core/app/proxyman/inbound.(*tcpWorker).Start(0xc00047b680, 0x63a5dfa9c5d738d5, 0xc0004b6fc0)
Aug 18 01:40:41 cIc.cc XrayR[119309]:         github.com/xtls/xray-core@v1.4.2/app/proxyman/inbound/worker.go:120 +0xb5
Aug 18 01:40:41 cIc.cc XrayR[119309]: github.com/xtls/xray-core/app/proxyman/inbound.(*AlwaysOnInboundHandler).Start(0xc0004b6fc0, 0xc00047eff0, 0xc00042a1a0)
Aug 18 01:40:41 cIc.cc XrayR[119309]:         github.com/xtls/xray-core@v1.4.2/app/proxyman/inbound/always.go:153 +0x66
Aug 18 01:40:41 cIc.cc XrayR[119309]: github.com/xtls/xray-core/app/proxyman/inbound.(*Manager).AddHandler(0xc0004b6380, 0x2289f70, 0xc00003e070, 0x228a670, 0xc0004b6fc0, 0x0, 0x0)
Aug 18 01:40:41 cIc.cc XrayR[119309]:         github.com/xtls/xray-core@v1.4.2/app/proxyman/inbound/inbound.go:54 +0x10b
Aug 18 01:40:41 cIc.cc XrayR[119309]: github.com/XrayR-project/XrayR/service/controller.(*Controller).addInbound(0xc0004ba990, 0xc00007ad20, 0xc00007ad20, 0x0)
Aug 18 01:40:41 cIc.cc XrayR[119309]:         github.com/XrayR-project/XrayR/service/controller/control.go:40 +0x1ae
Aug 18 01:40:41 cIc.cc XrayR[119309]: github.com/XrayR-project/XrayR/service/controller.(*Controller).addNewTag(0xc0004ba990, 0xc0004bc6e0, 0x0, 0x0)
Aug 18 01:40:41 cIc.cc XrayR[119309]:         github.com/XrayR-project/XrayR/service/controller/controller.go:238 +0x9c
Aug 18 01:40:41 cIc.cc XrayR[119309]: github.com/XrayR-project/XrayR/service/controller.(*Controller).Start(0xc0004ba990, 0x0, 0x0)
Aug 18 01:40:41 cIc.cc XrayR[119309]:         github.com/XrayR-project/XrayR/service/controller/controller.go:48 +0x105
Aug 18 01:40:41 cIc.cc XrayR[119309]: github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc0003fb600)
Aug 18 01:40:41 cIc.cc XrayR[119309]:         github.com/XrayR-project/XrayR/panel/panel.go:135 +0x63b
Aug 18 01:40:41 cIc.cc XrayR[119309]: main.main()
Aug 18 01:40:41 cIc.cc XrayR[119309]:         github.com/XrayR-project/XrayR/main/main.go:85 +0x1c5
Aug 18 01:40:41 cIc.cc systemd[1]: XrayR.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Aug 18 01:40:41 cIc.cc systemd[1]: XrayR.service: Failed with result 'exit-code'.

```
从 **panic: Calling Domain() on an IPv4Address.** 中推测可能是xray未获取到对接的ipv4

**Comment by RManLuo** [comment]
确认已正确设置ss端口

**Comment by atomiky** [comment]
请问怎么解决的啊

**Comment by caiqing7831** [comment]
来群里问吧，没必要issues
