### ISSUE TITLE
对接sspanel的shadowsocks2022提示missing key

### ISSUE THREAD

**Issue by x-liao** [XrayR-project/XrayR#552]
Custom_config
```
{
    "offset_port_node": "8080",
    "method": "2022-blake3-aes-128-gcm",
    "server_key": "zP6flOl9PSsHr019zGSV6Q=="
}
```
xrayr log
```
Dec 16 11:57:38 smoke systemd[1]: Stopped XrayR.service - XrayR Service.
Dec 16 11:57:38 smoke systemd[1]: Started XrayR.service - XrayR Service.
Dec 16 11:57:38 smoke XrayR[158609]: XrayR 0.9.1 (A Xray backend that supports many panels)
Dec 16 11:57:38 smoke XrayR[158609]: 2023/12/16 11:57:38 Start the panel..
Dec 16 11:57:38 smoke XrayR[158609]: 2023/12/16 11:57:38 Xray Core Version: 1.8.4
Dec 16 11:57:38 smoke XrayR[158609]: 2023/12/16 11:57:38 [Debug] app/log: Logger started
Dec 16 11:57:38 smoke XrayR[158609]: 2023/12/16 11:57:38 [Info] app/dns: DNS: created localhost client
Dec 16 11:57:38 smoke XrayR[158609]: 2023/12/16 11:57:38 [Warning] core: Xray 1.8.4 started
Dec 16 11:57:38 smoke XrayR[158609]: 2023/12/16 11:57:38 proxy/shadowsocks_2022: missing key
Dec 16 11:57:38 smoke XrayR[158609]: panic: proxy/shadowsocks_2022: missing key
Dec 16 11:57:38 smoke XrayR[158609]: goroutine 1 [running]:
Dec 16 11:57:38 smoke XrayR[158609]: log.Panic({0xc0008b7c68?, 0xc0006da100?, 0xc0008b7ce8?})
Dec 16 11:57:38 smoke XrayR[158609]:         log/log.go:432 +0x5a
Dec 16 11:57:38 smoke XrayR[158609]: github.com/XrayR-project/XrayR/service/controller.(*Controller).Start(0xc0006da700)
Dec 16 11:57:38 smoke XrayR[158609]:         github.com/XrayR-project/XrayR/service/controller/controller.go:88 +0x26f
Dec 16 11:57:38 smoke XrayR[158609]: github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc00052b400)
Dec 16 11:57:38 smoke XrayR[158609]:         github.com/XrayR-project/XrayR/panel/panel.go:208 +0x596
Dec 16 11:57:38 smoke XrayR[158609]: main.main()
Dec 16 11:57:38 smoke XrayR[158609]:         github.com/XrayR-project/XrayR/main/main.go:97 +0x233
Dec 16 11:57:38 smoke systemd[1]: XrayR.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 16 11:57:38 smoke systemd[1]: XrayR.service: Failed with result 'exit-code'.
```

**Comment by thank243** [comment]
DisableLocalREALITYConfig: true  # disable local reality config

**Comment by x-liao** [comment]
> ```
>   DisableLocalREALITYConfig: true  # disable local reality config
> ```

该配置并不起作用
以下是XrayR的配置
```yml
Log:
  Level: warning # Log level: none, error, warning, info, debug 
  AccessPath: # /etc/XrayR/access.Log
  ErrorPath: # /etc/XrayR/error.log
DnsConfigPath: # /etc/XrayR/dns.json # Path to dns config, check https://xtls.github.io/config/dns.html for help
RouteConfigPath: # /etc/XrayR/route.json # Path to route config, check https://xtls.github.io/config/routing.html for help
InboundConfigPath: # /etc/XrayR/custom_inbound.json # Path to custom inbound config, check https://xtls.github.io/config/inbound.html for help
OutboundConfigPath: # /etc/XrayR/custom_outbound.json # Path to custom outbound config, check https://xtls.github.io/config/outbound.html for help
ConnectionConfig:
  Handshake: 4 # Handshake time limit, Second
  ConnIdle: 30 # Connection idle time limit, Second
  UplinkOnly: 2 # Time limit when the connection downstream is closed, Second
  DownlinkOnly: 4 # Time limit when the connection is closed after the uplink is closed, Second
  BufferSize: 64 # The internal cache size of each connection, kB
Nodes:
  - PanelType: "SSpanel" # Panel type: SSpanel, NewV2board, PMpanel, Proxypanel, V2RaySocks, GoV2Panel
    ApiConfig:
      ApiHost: "https://XXXXX"
      ApiKey: "XXXX"
      NodeID: 16
      NodeType: Shadowsocks # Node type: V2ray, Shadowsocks, Trojan, Shadowsocks-Plugin
      Timeout: 30 # Timeout for the api request
      EnableVless: false # Enable Vless for V2ray Type
      VlessFlow: "xtls-rprx-vision" # Only support vless
      SpeedLimit: 0 # Mbps, Local settings will replace remote settings, 0 means disable
      DeviceLimit: 0 # Local settings will replace remote settings, 0 means disable
      RuleListPath: # /etc/XrayR/rulelist Path to local rulelist file
      DisableCustomConfig: false # disable custom config for sspanel
    ControllerConfig:
      ListenIP: 0.0.0.0 # IP address you want to listen
      SendIP: 0.0.0.0 # IP address you want to send pacakage
      UpdatePeriodic: 60 # Time to update the nodeinfo, how many sec.
      EnableDNS: false # Use custom DNS config, Please ensure that you set the dns.json well
      DNSType: AsIs # AsIs, UseIP, UseIPv4, UseIPv6, DNS strategy
      EnableProxyProtocol: false # Only works for WebSocket and TCP
      AutoSpeedLimitConfig:
        Limit: 0 # Warned speed. Set to 0 to disable AutoSpeedLimit (mbps)
        WarnTimes: 0 # After (WarnTimes) consecutive warnings, the user will be limited. Set to 0 to punish overspeed user immediately.
        LimitSpeed: 0 # The speedlimit of a limited user (unit: mbps)
        LimitDuration: 0 # How many minutes will the limiting last (unit: minute)
      GlobalDeviceLimitConfig:
        Enable: false # Enable the global device limit of a user
        RedisAddr: 127.0.0.1:6379 # The redis server address
        RedisPassword: YOUR PASSWORD # Redis password
        RedisDB: 0 # Redis DB
        Timeout: 5 # Timeout for redis request
        Expiry: 60 # Expiry time (second)
      EnableFallback: false # Only support for Trojan and Vless
      FallBackConfigs:  # Support multiple fallbacks
        - SNI: # TLS SNI(Server Name Indication), Empty for any
          Alpn: # Alpn, Empty for any
          Path: # HTTP PATH, Empty for any
          Dest: 80 # Required, Destination of fallback, check https://xtls.github.io/config/features/fallback.html for details.
          ProxyProtocolVer: 0 # Send PROXY protocol version, 0 for disable
      DisableLocalREALITYConfig: true  # disable local reality config
      EnableREALITY: false # Enable REALITY
      REALITYConfigs:
        Show: true # Show REALITY debug
        Dest: www.smzdm.com:443 # Required, Same as fallback
        ProxyProtocolVer: 0 # Send PROXY protocol version, 0 for disable
        ServerNames: # Required, list of available serverNames for the client, * wildcard is not supported at the moment.
          - www.smzdm.com
        PrivateKey: kOsBHSgxhAfCeQIQyJvupiXTmQrMmsqi6y6Wc5OQZXc # Required, execute './xray x25519' to generate.
        MinClientVer: # Optional, minimum version of Xray client, format is x.y.z.
        MaxClientVer: # Optional, maximum version of Xray client, format is x.y.z.
        MaxTimeDiff: 0 # Optional, maximum allowed time difference, unit is in milliseconds.
        ShortIds: # Required, list of available shortIds for the client, can be used to differentiate between different clients.
          - ""
          - 0123456789abcdef
      CertConfig:
        CertMode: dns # Option about how to get certificate: none, file, http, tls, dns. Choose "none" will forcedly disable the tls config.
        CertDomain: "node1.test.com" # Domain to cert
        CertFile: /etc/XrayR/cert/node1.test.com.cert # Provided if the CertMode is file
        KeyFile: /etc/XrayR/cert/node1.test.com.key
        Provider: alidns # DNS cert provider, Get the full support list here: https://go-acme.github.io/lego/dns/
        Email: test@me.com
        DNSEnv: # DNS ENV option used by DNS provider
          ALICLOUD_ACCESS_KEY: aaa
          ALICLOUD_SECRET_KEY: bbb
```

**Comment by thank243** [comment]
```json
{
    "offset_port_node": "8080",
    "method": "2022-blake3-aes-128-gcm",
    "server_key": "zP6flOl9PSsHr019zGSV6Q=="
}
```
Where you get this config?

**Comment by x-liao** [comment]
> ```json
> {
>     "offset_port_node": "8080",
>     "method": "2022-blake3-aes-128-gcm",
>     "server_key": "zP6flOl9PSsHr019zGSV6Q=="
> }
> ```
> 
> Where you get this config?

https://wiki.sspanel.org/#/custom-config?id=shadowsocks-2022

**Comment by thank243** [comment]
Those configurations is just used to client, not server.

**Comment by jack338c** [comment]
@thank243 
how to configurations this,I got the same issue
please help me,thanks
![Screenshot 2024-01-12 at 5 30 51 PM](https://github.com/XrayR-project/XrayR/assets/10782586/4ef83322-86ea-4109-9233-1d332c5cb834)

**Comment by qq280948982** [comment]
I have the same issue: proxy/shadowsocks_2022: missing key

**Comment by qq280948982** [comment]
> I have the same issue: proxy/shadowsocks_2022: missing key

I solved it by under confication: 

```
{
    "offset_port_user": "13701",
    "offset_port_node": "8080",
    "host": "your-host.com",
    "server_user": "your-host.com",
    "method": "chacha20-ietf-poly1305",
    "server_key": "your-server-key"
} 
```

the **server_key** can generated by command: `openssl rand -base64 16`
