### ISSUE TITLE
least ping strategy in load balancer

### ISSUE THREAD

**Issue by MrVb0** [XrayR-project/XrayR#557]
Hello, I was using the xray load balancer through the following configuration in the route, which I think uses the random strategy by default (it worked well) :
```
{
	
	  "balancers": [
{
  "tag": "balancerreality",
   "selector": [
                 "TUN1",
                 "TUN2",
                 "TUN3",
                 "TUN4",
                 "TUN5",
                 "TUN6",
                 "TUN7",
                 "TUN8",
                 "TUN9",
                 "TUN10",
                 "TUN11",
                 "TUN12",
                 "TUN13"
              ]
    }
],
	
  "domainStrategy": "IPOnDemand",
	
  "rules": [ 
      {
      "type": "field",
      "domain": [
        "geosite:category-ads-all"
      ],
      "outboundTag": "block"
    },    
    {
      "type": "field",
	  "network": "udp,tcp",
      "balancerTag": "balancerreality"
    }
  ]
} 
```
Now I want to use the leastPing strategy, but by adding the strategy section, xrayr gives an error.
i tested this :
```
{
	
	  "balancers": [
        {
  "tag": "balancerreality",
  "selector": [
                 "TUN1",
                 "TUN2",
                 "TUN3",
                 "TUN4",
                 "TUN5",
                 "TUN6",
                 "TUN7",
                 "TUN8",
                 "TUN9",
                 "TUN10",
                 "TUN11",
                 "TUN12",
                 "TUN13"
              ], 
	"strategy": {
          "type": "leastPing"
	            }
        }
  ],
	
  "domainStrategy": "IPOnDemand",
	
  "rules": [
      {
      "type": "field",
      "domain": [
        "geosite:category-ads-all"
      ],
      "outboundTag": "block"
    },    
    {
      "type": "field",
	  "network": "udp,tcp",
      "balancerTag": "balancerreality"
    }
  ]
}
```

and , also i tested this :
```
{
	
	  "balancers": [
        {
  "tag": "balancerreality",
  "selector": [
                 "TUN1",
                 "TUN2",
                 "TUN3",
                 "TUN4",
                 "TUN5",
                 "TUN6",
                 "TUN7",
                 "TUN8",
                 "TUN9",
                 "TUN10",
                 "TUN11",
                 "TUN12",
                 "TUN13"
              ], 
	"strategy": {
          "type": "leastPing"
	            }
        }
  ],
	
  "domainStrategy": "IPOnDemand",
	
  "rules": [
      {
      "type": "field",
      "domain": [
        "geosite:category-ads-all"
      ],
      "outboundTag": "block"
    },    
    {
      "type": "field",
	  "network": "udp,tcp",
      "balancerTag": "balancerreality"
    }
  ]
},
   "observatory": {
        "subjectSelector":[
                 "TUN1",
                 "TUN2",
                 "TUN3",
                 "TUN4",
                 "TUN5",
                 "TUN6",
                 "TUN7",
                 "TUN8",
                 "TUN9",
                 "TUN10",
                 "TUN11",
                 "TUN12",
                 "TUN13"
        ],
        "probeURL": "https://www.google.com/generate_204",
        "probeInterval": "1m"
      }
```

Error on xrayr log : 
```
Dec 20 13:33:50 khs.khs XrayR[1014618]: 2023/12/20 13:33:50 Failed to unmarshal Routing config: /etc/XrayR/route.json
Dec 20 13:33:50 khs.khs XrayR[1014618]: panic: Failed to unmarshal Routing config: /etc/XrayR/route.json
```

**Comment by thank243** [comment]
https://github.com/XTLS/Xray-core/issues/2777

**Comment by thank243** [comment]
```json
{
  "balancers": [
    {
      "tag": "balancerreality",
      "selector": [
        "TUN1",
        "TUN2",
        "TUN3",
        "TUN4",
        "TUN5",
        "TUN6",
        "TUN7",
        "TUN8",
        "TUN9",
        "TUN10",
        "TUN11",
        "TUN12",
        "TUN13"
      ],
      "strategy": {
        "type": "leastPing"
      }
    }
  ],
  "domainStrategy": "IPOnDemand",
  "rules": [
    {
      "type": "field",
      "domain": [
        "geosite:category-ads-all"
      ],
      "outboundTag": "block"
    },
    {
      "type": "field",
      "network": "udp,tcp",
      "balancerTag": "balancerreality"
    }
  ]
}
```
This config can be start.

**Comment by MrVb0** [comment]
@thank243 
error :
```
Dec 20 14:48:58 khs.khs XrayR[1055283]: panic: runtime error: invalid memory address or nil pointer dereference
Dec 20 14:48:58 khs.khs XrayR[1055283]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xc50a68]
Dec 20 14:48:58 khs.khs XrayR[1055283]: goroutine 58 [running]:
Dec 20 14:48:58 khs.khs XrayR[1055283]: github.com/xtls/xray-core/app/router.(*LeastPingStrategy).PickOutbound(0xc001801b40?, {0xc001ee20d0, 0xd, 0x3580e20?})
Dec 20 14:48:58 khs.khs XrayR[1055283]:         github.com/xtls/xray-core@v1.8.7-0.20231128163007-be21b1194b04/app/router/strategy_leastping.go:29 +0xa8
Dec 20 14:48:58 khs.khs XrayR[1055283]: github.com/xtls/xray-core/app/router.(*Balancer).PickOutbound(0xc000159700)
Dec 20 14:48:58 khs.khs XrayR[1055283]:         github.com/xtls/xray-core@v1.8.7-0.20231128163007-be21b1194b04/app/router/balancing.go:41 +0x10d
Dec 20 14:48:58 khs.khs XrayR[1055283]: github.com/xtls/xray-core/app/router.(*Rule).GetTag(...)
Dec 20 14:48:58 khs.khs XrayR[1055283]:         github.com/xtls/xray-core@v1.8.7-0.20231128163007-be21b1194b04/app/router/config.go:20
Dec 20 14:48:58 khs.khs XrayR[1055283]: github.com/xtls/xray-core/app/router.(*Router).PickRoute(0x4820dd8?, {0x4836b88?, 0xc001cba2a0?})
Dec 20 14:48:58 khs.khs XrayR[1055283]:         github.com/xtls/xray-core@v1.8.7-0.20231128163007-be21b1194b04/app/router/router.go:76 +0x5a
Dec 20 14:48:58 khs.khs XrayR[1055283]: github.com/XrayR-project/XrayR/app/mydispatcher.(*DefaultDispatcher).routedDispatch(0xc0010509a0, {0x4820dd8, 0xc001efcb10}, 0xc0010521a0, {{0x4821078, 0xc001f123bc}, 0x35, 0x3})
Dec 20 14:48:58 khs.khs XrayR[1055283]:         github.com/XrayR-project/XrayR/app/mydispatcher/default.go:441 +0x37c
Dec 20 14:48:58 khs.khs XrayR[1055283]: github.com/XrayR-project/XrayR/app/mydispatcher.(*DefaultDispatcher).Dispatch.func1()
Dec 20 14:48:58 khs.khs XrayR[1055283]:         github.com/XrayR-project/XrayR/app/mydispatcher/default.go:290 +0x5dd
Dec 20 14:48:58 khs.khs XrayR[1055283]: created by github.com/XrayR-project/XrayR/app/mydispatcher.(*DefaultDispatcher).Dispatch in goroutine 57
Dec 20 14:48:58 khs.khs XrayR[1055283]:         github.com/XrayR-project/XrayR/app/mydispatcher/default.go:263 +0x3ad
Dec 20 14:48:58 khs.khs systemd[1]: XrayR.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 20 14:48:58 khs.khs systemd[1]: XrayR.service: Failed with result 'exit-code'.
```

**Comment by thank243** [comment]
You can Goto xray-core for helping.

**Comment by MrVb0** [comment]
@thank243 I noticed that for the least ping strategy to work, "observatory" must be in the configuration.
Where and which file should I place this observatory section?

**Comment by xxntmctx** [comment]
> 我注意到，要使最小 ping 策略起作用，“observatory”必须在配置中。我应该把这个 observatory 部分放在哪里以及放在哪个文件？

同问
