### ISSUE TITLE
运行中报错

### ISSUE THREAD

**Issue by xuchangbin** [XrayR-project/XrayR#6]
主机配置1H1G，加载用户3000+，在线用户只有个位数，会报以下错：
```
3月 29 15:35:52 VM-4-12-centos XrayR[25750]: 2021/03/29 15:35:52.462883 ERROR RESTY Get "https://***.**/mod_mu/users?key=***&node_id=22": context deadline exceeded (Client.Timeout exceeded while awaiting headers), Attempt 2
3月 29 15:35:54 VM-4-12-centos XrayR[25750]: 2021/03/29 15:35:54 113.*.*.39:42102 accepted udp:216.*.*.67:443 [V2ray_80 >> V2ray_80] email: V2ray_80|***@gmail.com|5846
3月 29 15:35:54 VM-4-12-centos XrayR[25750]: 2021/03/29 15:35:54.906772 ERROR RESTY Post "https://*.*/mod_mu/users/aliveip?key=*&node_id=22": context deadline exceeded (Client.Timeout exceeded while awaiting headers), Attempt 2
3月 29 15:35:57 VM-4-12-centos XrayR[25750]: 2021/03/29 15:35:57.619901 ERROR RESTY Get "https://*.*/mod_mu/users?key=*&node_id=22": context deadline exceeded (Client.Timeout exceeded while awaiting headers), Attempt 3
3月 29 15:35:58 VM-4-12-centos XrayR[25750]: 2021/03/29 15:35:58 Report 3 online users
3月 29 15:36:00 VM-4-12-centos XrayR[25750]: 2021/03/29 15:36:00 tcp:119.*.*.101:4082 accepted tcp:clients4.google.com:443 [V2ray_80 >> V2ray_80] email: V2ray_80|*@qq.com|5500
3月 29 15:36:02 VM-4-12-centos XrayR[25750]: 2021/03/29 15:36:02.956253 ERROR RESTY context deadline exceeded (Client.Timeout or context cancellation while reading body), Attempt 4
3月 29 15:36:03 VM-4-12-centos XrayR[25750]: panic: runtime error: invalid memory address or nil pointer dereference
3月 29 15:36:03 VM-4-12-centos XrayR[25750]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x16918a8]
3月 29 15:36:03 VM-4-12-centos XrayR[25750]: goroutine 883 [running]:
3月 29 15:36:03 VM-4-12-centos XrayR[25750]: github.com/XrayR-project/XrayR/api/sspanel.(*APIClient).GetUserList(0xc00051fef0, 0xc0002a05a0, 0x8, 0xc0004b76b0)
3月 29 15:36:03 VM-4-12-centos XrayR[25750]: github.com/XrayR-project/XrayR/api/sspanel/sspanel.go:139 +0x368
3月 29 15:36:03 VM-4-12-centos XrayR[25750]: github.com/XrayR-project/XrayR/service/controller.(*Controller).nodeInfoMonitor(0xc000513c20, 0x1d04d60, 0xc003b2d840)
3月 29 15:36:03 VM-4-12-centos XrayR[25750]: github.com/XrayR-project/XrayR/service/controller/controller.go:167 +0x36e
3月 29 15:36:03 VM-4-12-centos XrayR[25750]: github.com/xtls/xray-core/common/task.(*Periodic).checkedExecute(0xc003b2d830, 0x0, 0x0)
3月 29 15:36:03 VM-4-12-centos XrayR[25750]: github.com/xtls/xray-core@v1.4.0/common/task/periodic.go:32 +0x5e
3月 29 15:36:03 VM-4-12-centos XrayR[25750]: github.com/xtls/xray-core/common/task.(*Periodic).checkedExecute.func1()
3月 29 15:36:03 VM-4-12-centos XrayR[25750]: github.com/xtls/xray-core@v1.4.0/common/task/periodic.go:47 +0x2a
3月 29 15:36:03 VM-4-12-centos XrayR[25750]: created by time.goFunc
3月 29 15:36:03 VM-4-12-centos XrayR[25750]: time/sleep.go:180 +0x45
3月 29 15:36:03 VM-4-12-centos systemd[1]: XrayR.service: main process exited, code=exited, status=2/INVALIDARGUMENT
3月 29 15:36:03 VM-4-12-centos systemd[1]: Unit XrayR.service entered failed state.
3月 29 15:36:03 VM-4-12-centos systemd[1]: XrayR.service failed.
3月 29 15:36:08 VM-4-12-centos systemd[1]: XrayR.service holdoff time over, scheduling restart.
3月 29 15:36:08 VM-4-12-centos systemd[1]: Stopped XrayR Service.
3月 29 15:36:08 VM-4-12-centos systemd[1]: Started XrayR Service.
```
是主机配置太低导致的吗？还是有别的优化配置？

**Comment by crackair** [comment]
感觉是面板网络问题。
