### ISSUE TITLE
使用最新的docker镜像v0.9.4部署后出现strconv.ParseInt

### ISSUE THREAD

**Issue by draco-china** [XrayR-project/XrayR#663]
节点类型 trojan
日志文件 ip 已修改
```
xrayr  | time="2024-07-22T15:51:07+08:00" level=info msg="The panel version is expired, it is recommended to update immediately"
xrayr | time="2024-07-22T15:51:07+08:00" level=panic msg="Panel Start failed: parse node info failed: {\"node_group\":0,\"node_class\":0,\"node_speedlimit\":0,\"traffic_rate\":0,\"sort\":14,\"server\":\"0.0.0.0\",\"type\":\"SSPanel-UIM\",\"custom_config\":{\"offset_port_node\":\"158\",\"allow_insecure\":\"1\"},\"version\":\"24.0.0\"}, \nError: strconv.ParseInt: parsing \"\": invalid syntax"
xrayr  | panic: (*logrus.Entry) 0xc0011701c0
xrayr  | 
xrayr  | goroutine 1 [running]:
xrayr  | github.com/sirupsen/logrus.(*Entry).log(0xc0011700e0, 0x0, {0xc001bb4140, 0x132})
xrayr  |      github.com/sirupsen/logrus@v1.9.3/entry.go:260 +0x491
xrayr  | github.com/sirupsen/logrus.(*Entry).Log(0xc0011700e0, 0x0, {0xc001b1fa00?, 0x1?, 0x1?})
xrayr  |      github.com/sirupsen/logrus@v1.9.3/entry.go:304 +0x48
xrayr  | github.com/sirupsen/logrus.(*Entry).Logf(0xc0011700e0, 0x0, {0x448770c?, 0x14?}, {0xc001b1faf0?, 0x6?, 0xc00146f1d8?})
xrayr  |      github.com/sirupsen/logrus@v1.9.3/entry.go:349 +0x7c
```

**Comment by theresaarcher** [comment]
The XrayR panel failed to start due to an error in parsing node information. The specific error encountered is strconv.ParseInt: parsing "": invalid syntax. This indicates that there was an attempt to parse an empty string or a non-integer value as an integer.

- Review the configuration file or database where the node information is stored.
- Ensure that all fields expected to contain integers are correctly populated with integer values and not empty strings or other non-integer values.

The panel version mentioned is "24.0.0". It is recommended to update to the latest version to avoid potential issues and take advantage of new features and bug fixes.
