### ISSUE TITLE
启动XrayR失败

### ISSUE THREAD

**Issue by Chun-QiuCC** [XrayR-project/XrayR#675]
LOG：
```
Aug 02 07:44:38 tw1.****.top systemd[1]: XrayR.service: Scheduled restart job, restart counter is at 57.
Aug 02 07:44:38 tw1.****.top systemd[1]: Stopped XrayR Service.
Aug 02 07:44:38 tw1.****.top systemd[1]: Started XrayR Service.
Aug 02 07:44:38 tw1.****.top XrayR[17758]: XrayR 0.9.4 (A Xray backend that supports many panels)
Aug 02 07:44:38 tw1.****.top XrayR[17758]: time="2024-08-02T07:44:38Z" level=info msg="Start the panel.."
Aug 02 07:44:38 tw1.****.top XrayR[17758]: time="2024-08-02T07:44:38Z" level=panic msg="failed to create instance: app/router: this rule has no effective fields"
Aug 02 07:44:38 tw1.****.top XrayR[17758]: panic: (*logrus.Entry) 0xc0019abea0
Aug 02 07:44:38 tw1.****.top XrayR[17758]: goroutine 1 [running]:
Aug 02 07:44:38 tw1.****.top XrayR[17758]: github.com/sirupsen/logrus.(*Entry).log(0xc0019abe30, 0x0, {0xc0014a6550, 0x48})
Aug 02 07:44:38 tw1.****.top XrayR[17758]:         github.com/sirupsen/logrus@v1.9.3/entry.go:260 +0x491
Aug 02 07:44:38 tw1.****.top XrayR[17758]: github.com/sirupsen/logrus.(*Entry).Log(0xc0019abe30, 0x0, {0xc0021f7598?, 0x1?, 0x1?})
Aug 02 07:44:38 tw1.****.top XrayR[17758]:         github.com/sirupsen/logrus@v1.9.3/entry.go:304 +0x48
Aug 02 07:44:38 tw1.****.top XrayR[17758]: github.com/sirupsen/logrus.(*Entry).Logf(0xc0019abe30, 0x0, {0x44a83ad?, 0xc0021f75f8?}, {0xc0021f77b8?, 0xc0021f7808?, 0xc0000bf4f0?})
Aug 02 07:44:38 tw1.****.top XrayR[17758]:         github.com/sirupsen/logrus@v1.9.3/entry.go:349 +0x7c
Aug 02 07:44:38 tw1.****.top XrayR[17758]: github.com/sirupsen/logrus.(*Logger).Logf(0x77f1160, 0x0, {0x44a83ad, 0x1d}, {0xc0021f77b8, 0x1, 0x1})
Aug 02 07:44:38 tw1.****.top XrayR[17758]:         github.com/sirupsen/logrus@v1.9.3/logger.go:154 +0x7c
Aug 02 07:44:38 tw1.****.top XrayR[17758]: github.com/sirupsen/logrus.(*Logger).Panicf(...)
Aug 02 07:44:38 tw1.****.top XrayR[17758]:         github.com/sirupsen/logrus@v1.9.3/logger.go:195
Aug 02 07:44:38 tw1.****.top XrayR[17758]: github.com/sirupsen/logrus.Panicf(...)
Aug 02 07:44:38 tw1.****.top XrayR[17758]:         github.com/sirupsen/logrus@v1.9.3/exported.go:219
Aug 02 07:44:38 tw1.****.top XrayR[17758]: github.com/XrayR-project/XrayR/panel.(*Panel).loadCore(0x77f1160?, 0xc0019aae00)
Aug 02 07:44:38 tw1.****.top XrayR[17758]:         github.com/XrayR-project/XrayR/panel/panel.go:155 +0xd4c
Aug 02 07:44:38 tw1.****.top XrayR[17758]: github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc00199d1c0)
Aug 02 07:44:38 tw1.****.top XrayR[17758]:         github.com/XrayR-project/XrayR/panel/panel.go:167 +0xdf
Aug 02 07:44:38 tw1.****.top XrayR[17758]: github.com/XrayR-project/XrayR/cmd.run()
Aug 02 07:44:38 tw1.****.top XrayR[17758]:         github.com/XrayR-project/XrayR/cmd/root.go:106 +0x1c5
Aug 02 07:44:38 tw1.****.top XrayR[17758]: github.com/XrayR-project/XrayR/cmd.init.func1(0xc0019ac600?, {0x445389d?, 0x4?, 0x445378d?})
Aug 02 07:44:38 tw1.****.top XrayR[17758]:         github.com/XrayR-project/XrayR/cmd/root.go:27 +0x13
Aug 02 07:44:38 tw1.****.top XrayR[17758]: github.com/spf13/cobra.(*Command).execute(0x780c840, {0xc000072910, 0x2, 0x2})
Aug 02 07:44:38 tw1.****.top XrayR[17758]:         github.com/spf13/cobra@v1.8.0/command.go:987 +0xab1
Aug 02 07:44:38 tw1.****.top XrayR[17758]: github.com/spf13/cobra.(*Command).ExecuteC(0x780c840)
Aug 02 07:44:38 tw1.****.top XrayR[17758]:         github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
Aug 02 07:44:38 tw1.****.top XrayR[17758]: github.com/spf13/cobra.(*Command).Execute(...)
Aug 02 07:44:38 tw1.****.top XrayR[17758]:         github.com/spf13/cobra@v1.8.0/command.go:1039
Aug 02 07:44:38 tw1.****.top XrayR[17758]: github.com/XrayR-project/XrayR/cmd.Execute(...)
Aug 02 07:44:38 tw1.****.top XrayR[17758]:         github.com/XrayR-project/XrayR/cmd/root.go:120
Aug 02 07:44:38 tw1.****.top XrayR[17758]: main.main()
Aug 02 07:44:38 tw1.****.top XrayR[17758]:         github.com/XrayR-project/XrayR/main.go:10 +0x1a
Aug 02 07:44:38 tw1.****.top systemd[1]: XrayR.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Aug 02 07:44:38 tw1.****.top systemd[1]: XrayR.service: Failed with result 'exit-code'.
```
config.yml:
```
Log:
  Level: warning # Log level: none, error, warning, info, debug
  AccessPath: # /etc/XrayR/access.Log
  ErrorPath: # /etc/XrayR/error.log
DnsConfigPath: # /etc/XrayR/dns.json # Path to dns config, check https://xtls.github.io/config/dns.html for help
RouteConfigPath: /etc/XrayR/route.json # Path to route config, check https://xtls.github.io/config/routing.html for help
InboundConfigPath: # /etc/XrayR/custom_inbound.json # Path to custom inbound config, check https://xtls.github.io/config/inbound.html for help
OutboundConfigPath: /etc/XrayR/custom_outbound.json # Path to custom outbound config, check https://xtls.github.io/config/outbound.html for help
ConnectionConfig:
  Handshake: 4 # Handshake time limit, Second
  ConnIdle: 30 # Connection idle time limit, Second
  UplinkOnly: 2 # Time limit when the connection downstream is closed, Second
  DownlinkOnly: 4 # Time limit when the connection is closed after the uplink is closed, Second
  BufferSize: 64 # The internal cache size of each connection, kB
Nodes:
  - PanelType: "NewV2board" # Panel type: SSpanel, NewV2board, PMpanel, Proxypanel, V2RaySocks, GoV2Panel, BunPanel
    ApiConfig:
      ApiHost: "https://www.****.top"
      ApiKey: "****************"
      NodeID: 4
      NodeType: V2ray # Node type: V2ray, Vmess, Vless, Shadowsocks, Trojan, Shadowsocks-Plugin
      Timeout: 30 # Timeout for the api request
      EnableVless: true # Enable Vless for V2ray Type
      #VlessFlow: "xtls-rprx-vision" # Only support vless
      SpeedLimit: 0 # Mbps, Local settings will replace remote settings, 0 means disable
      DeviceLimit: 0 # Local settings will replace remote settings, 0 means disable
      RuleListPath: # /etc/XrayR/rulelist Path to local rulelist file
      DisableCustomConfig: false # disable custom config for sspanel
    ControllerConfig:
      ListenIP: 0.0.0.0 # IP address you want to listen
      SendIP: 0.0.0.0 # IP address you want to send pacakage
      UpdatePeriodic: 60 # Time to update the nodeinfo, how many sec.
      EnableDNS: false # Use custom DNS config, Please ensure that you set the dns.json well
      DNSType: AsIs # AsIs, UseIP, UseIPv4, UseIPv6, DNS strategy
      EnableProxyProtocol: false # Only works for WebSocket and TCP
      AutoSpeedLimitConfig:
        Limit: 0 # Warned speed. Set to 0 to disable AutoSpeedLimit (mbps)
        WarnTimes: 0 # After (WarnTimes) consecutive warnings, the user will be limited. Set to 0 to punish overspeed user immediately.
        LimitSpeed: 0 # The speedlimit of a limited user (unit: mbps)
        LimitDuration: 0 # How many minutes will the limiting last (unit: minute)
      GlobalDeviceLimitConfig:
        Enable: false # Enable the global device limit of a user
        RedisNetwork: tcp # Redis protocol, tcp or unix
        RedisAddr: 127.0.0.1:6379 # Redis server address, or unix socket path
        RedisUsername: # Redis username
        RedisPassword: YOUR PASSWORD # Redis password
        RedisDB: 0 # Redis DB
        Timeout: 5 # Timeout for redis request
        Expiry: 60 # Expiry time (second)
      EnableFallback: false # Only support for Trojan and Vless
      FallBackConfigs:  # Support multiple fallbacks
        - SNI: # TLS SNI(Server Name Indication), Empty for any
          Alpn: # Alpn, Empty for any
          Path: # HTTP PATH, Empty for any
          Dest: 80 # Required, Destination of fallback, check https://xtls.github.io/config/features/fallback.html for details.
          ProxyProtocolVer: 0 # Send PROXY protocol version, 0 for disable
      DisableLocalREALITYConfig: false  # disable local reality config
      EnableREALITY: true # Enable REALITY
      REALITYConfigs:
        Show: false # Show REALITY debug
        Dest: www.amazon.com:443 # Required, Same as fallback
        ProxyProtocolVer: 0 # Send PROXY protocol version, 0 for disable
        ServerNames: # Required, list of available serverNames for the client, * wildcard is not supported at the moment.
          - www.amazon.com
        PrivateKey: YOUR_PRIVATE_KEY # Required, execute './XrayR x25519' to generate.
        MinClientVer: # Optional, minimum version of Xray client, format is x.y.z.
        MaxClientVer: # Optional, maximum version of Xray client, format is x.y.z.
        MaxTimeDiff: 0 # Optional, maximum allowed time difference, unit is in milliseconds.
        ShortIds: # Required, list of available shortIds for the client, can be used to differentiate between different clients.
          - ""
      CertConfig:
        CertMode: dns # Option about how to get certificate: none, file, http, tls, dns. Choose "none" will forcedly disable the tls config.
        CertDomain: "node1.test.com" # Domain to cert
        CertFile: /etc/XrayR/cert/node1.test.com.cert # Provided if the CertMode is file
        KeyFile: /etc/XrayR/cert/node1.test.com.key
        Provider: alidns # DNS cert provider, Get the full support list here: https://go-acme.github.io/lego/dns/
        Email: test@me.com
        DNSEnv: # DNS ENV option used by DNS provider
          ALICLOUD_ACCESS_KEY: aaa
          ALICLOUD_SECRET_KEY: bbb

#  - PanelType: "SSpanel" # Panel type: SSpanel, V2board, NewV2board, PMpanel, Proxypanel, V2RaySocks, GoV2Panel
#    ApiConfig:
#      ApiHost: "http://127.0.0.1:668"
#      ApiKey: "123"
#      NodeID: 41
#      NodeType: V2ray # Node type: V2ray, Shadowsocks, Trojan, Shadowsocks-Plugin
#      Timeout: 30 # Timeout for the api request
#      EnableVless: false # Enable Vless for V2ray Type
#      VlessFlow: "xtls-rprx-vision" # Only support vless
#      SpeedLimit: 0 # Mbps, Local settings will replace remote settings, 0 means disable
#      DeviceLimit: 0 # Local settings will replace remote settings, 0 means disable
#      RuleListPath: # /etc/XrayR/rulelist Path to local rulelist file
#    ControllerConfig:
#      ListenIP: 0.0.0.0 # IP address you want to listen
#      SendIP: 0.0.0.0 # IP address you want to send pacakage
#      UpdatePeriodic: 60 # Time to update the nodeinfo, how many sec.
#      EnableDNS: false # Use custom DNS config, Please ensure that you set the dns.json well
#      DNSType: AsIs # AsIs, UseIP, UseIPv4, UseIPv6, DNS strategy
#      EnableProxyProtocol: false # Only works for WebSocket and TCP
#      AutoSpeedLimitConfig:
#        Limit: 0 # Warned speed. Set to 0 to disable AutoSpeedLimit (mbps)
#        WarnTimes: 0 # After (WarnTimes) consecutive warnings, the user will be limited. Set to 0 to punish overspeed user immediately.
#        LimitSpeed: 0 # The speedlimit of a limited user (unit: mbps)
#        LimitDuration: 0 # How many minutes will the limiting last (unit: minute)
#      GlobalDeviceLimitConfig:
#        Enable: false # Enable the global device limit of a user
#        RedisAddr: 127.0.0.1:6379 # The redis server address
#        RedisPassword: YOUR PASSWORD # Redis password
#        RedisDB: 0 # Redis DB
#        Timeout: 5 # Timeout for redis request
#        Expiry: 60 # Expiry time (second)
#      EnableFallback: false # Only support for Trojan and Vless
#      FallBackConfigs:  # Support multiple fallbacks
#        - SNI: # TLS SNI(Server Name Indication), Empty for any
#          Alpn: # Alpn, Empty for any
#          Path: # HTTP PATH, Empty for any
#          Dest: 80 # Required, Destination of fallback, check https://xtls.github.io/config/features/fallback.html for details.
#          ProxyProtocolVer: 0 # Send PROXY protocol version, 0 for disable
#      EnableREALITY: true # Enable REALITY
#      REALITYConfigs:
#        Show: true # Show REALITY debug
#        Dest: www.amazon.com:443 # Required, Same as fallback
#        ProxyProtocolVer: 0 # Send PROXY protocol version, 0 for disable
#        ServerNames: # Required, list of available serverNames for the client, * wildcard is not supported at the moment.
#          - www.amazon.com
#        PrivateKey: YOUR_PRIVATE_KEY # Required, execute './XrayR x25519' to generate.
#        MinClientVer: # Optional, minimum version of Xray client, format is x.y.z.
#        MaxClientVer: # Optional, maximum version of Xray client, format is x.y.z.
#        MaxTimeDiff: 0 # Optional, maximum allowed time difference, unit is in milliseconds.
#        ShortIds: # Required, list of available shortIds for the client, can be used to differentiate between different clients.
#          - ""
#          - 0123456789abcdef
#      CertConfig:
#        CertMode: dns # Option about how to get certificate: none, file, http, tls, dns. Choose "none" will forcedly disable the tls config.
#        CertDomain: "node1.test.com" # Domain to cert
#        CertFile: /etc/XrayR/cert/node1.test.com.cert # Provided if the CertMode is file
#        KeyFile: /etc/XrayR/cert/node1.test.com.key
#        Provider: alidns # DNS cert provider, Get the full support list here: https://go-acme.github.io/lego/dns/
#        Email: test@me.com
#        DNSEnv: # DNS ENV option used by DNS provider
#          ALICLOUD_ACCESS_KEY: aaa
#          ALICLOUD_SECRET_KEY: bbb

```
xboard config:
![1](https://us1.minio.cn86.dev/drive/xboard2.png)

我的香港节点与本节点配置方式一致，香港节点可正常运行，但本节点报错

**Comment by Chun-QiuCC** [comment]
我没有更改过我的route配置，但按照此issus的方法移除了route.json中的socks5-warp后成功启动了
#83
