### ISSUE TITLE
关于适配最新的xray core 1.5.0版

### ISSUE THREAD

**Issue by moranno** [XrayR-project/XrayR#71]
刚刚用xrayr 0.7.2，替换了最新编译的xray core 1.5.0 63d0cb1，节点为shadowsocks时，启动失败：
```
panic: Can't get all input parameters
XrayR[258325]: goroutine 1 [running]:
XrayR[258325]: github.com/xtls/xray-core/core.(*resolution).resolve(0xc00066d7b8, {0xc0004c0b00, 0x8, 0x8})
XrayR[258325]: /code/go/src/github.com/XrayR-project/XrayR/vendor/github.com/xtls/xray-core/core/xray.go:70 +0x532
XrayR[258325]: github.com/xtls/xray-core/core.(*Instance).RequireFeatures(0xc000490230, {0x1924540, 0xc000559800})
XrayR[258325]: /code/go/src/github.com/XrayR-project/XrayR/vendor/github.com/xtls/xray-core/core/xray.go:291 +0x219
...
```
希望能适配更新下，63d0cb1修正了xray中ss实现的重大漏洞。

**Comment by RManLuo** [comment]
Xray-core 1.5版本对dispatcher进行了重构，需要修改迁移部分代码才能更新。由于现在1.5仍然是pre-release，等正式发布之后会进行跟进。

**Comment by RManLuo** [comment]
f398dca4819b77c98e28d8a7b5521ab541012839
