### ISSUE TITLE
套了warp的机子如果在sspanel填真实ip则会报错

### ISSUE THREAD

**Issue by DocWho22** [XrayR-project/XrayR#72]
8.56.90.11是套warp的ip，WARP 并不提供公网 IP 地址，它是以 NAT 的方式去访问外部网络，即只能用于对外网络访问，不能用于对 VPS 本机访问。就是说用这个ip无法访问到服务器。

但如果在sspanel填真实ip，也就是`23.123.234.56;port=80#1234;server=23.123.234.56`，就会出现如下的报错
```shell
Nov 03 00:04:41 host-23-123-234-56-by systemd[1]: XrayR.service: Service RestartSec=10s expired, scheduling restart.
Nov 03 00:04:41 host-23-123-234-56-by systemd[1]: XrayR.service: Scheduled restart job, restart counter is at 34.
Nov 03 00:04:41 host-23-123-234-56-by systemd[1]: Stopped XrayR Service.
Nov 03 00:04:41 host-23-123-234-56-by systemd[1]: Started XrayR Service.
Nov 03 00:04:41 host-23-123-234-56-by XrayR[15631]: XrayR 0.7.2 (A Xray backend that supports many panels)
Nov 03 00:04:41 host-23-123-234-56-by XrayR[15631]: 2021/11/03 00:04:41 Start the panel..
Nov 03 00:04:41 host-23-123-234-56-by XrayR[15631]: 2021/11/03 00:04:41 Xray Core Version: 1.4.5
Nov 03 00:04:42 host-23-123-234-56-by XrayR[15631]: 2021/11/03 00:04:42 Panel Start fialed: Ret {"ret":0,"data":"Token or IP is invalid. Now, your IP address is 8.56.90.11"} invalid
Nov 03 00:04:42 host-23-123-234-56-by XrayR[15631]: panic: Panel Start fialed: Ret {"ret":0,"data":"Token or IP is invalid. Now, your IP address is 8.56.90.11"} invalid
Nov 03 00:04:42 host-23-123-234-56-by XrayR[15631]: goroutine 1 [running]:
Nov 03 00:04:42 host-23-123-234-56-by XrayR[15631]: log.Panicf({0x1d5a2d1, 0x0}, {0xc00061fea8, 0xc00044e310, 0xc0002dfe90})
Nov 03 00:04:42 host-23-123-234-56-by XrayR[15631]:         log/log.go:361 +0x67
Nov 03 00:04:42 host-23-123-234-56-by XrayR[15631]: github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc0003e9880)
Nov 03 00:04:42 host-23-123-234-56-by XrayR[15631]:         github.com/XrayR-project/XrayR/panel/panel.go:174 +0x588
Nov 03 00:04:42 host-23-123-234-56-by XrayR[15631]: main.main()
Nov 03 00:04:42 host-23-123-234-56-by XrayR[15631]:         github.com/XrayR-project/XrayR/main/main.go:85 +0x1b6
Nov 03 00:04:42 host-23-123-234-566-by systemd[1]: XrayR.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Nov 03 00:04:42 host-23-123-234-56-by systemd[1]: XrayR.service: Failed with result 'exit-code'.
```
而把真实ip换成warp的ip，也就是8.56.90.11后不会报错，但实际上面板前端还是红色。无法使用代理节点。

**Comment by meepuru** [comment]
这不是后端的问题, 请尝试在 sspanel 中增加一个不显示的占位节点并在地址栏中填写你的 warp 地址

**Comment by RManLuo** [comment]
This bug is NOT related to XrayR.
